// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: ['dist/*', '.expo/*', '.amplify/**', 'docs/*', '**/*.dc.html'],
  },
  {
    // `$amplify/env/<function>` modules are generated by Amplify when the backend is deployed.
    rules: {
      'import/no-unresolved': ['error', { ignore: ['^\\$amplify/'] }],
    },
  },
  {
    // Phase 1 (theme separation): colours come from src/theme through useTheme(). Warnings while the
    // remaining files are migrated; these become errors in batch 4.
    ignores: ['src/theme/**'],
    rules: {
      'no-restricted-syntax': [
        'warn',
        {
          selector: 'Literal[value=/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/]',
          message: 'Hex colours belong in src/theme; read them with useTheme().',
        },
      ],
      'no-restricted-imports': [
        'warn',
        {
          paths: [{ name: '@/theme', importNames: ['colors'], message: 'Deprecated: read colours with useTheme() (or makeStyles).' }],
        },
      ],
    },
  },
]);
