// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require('eslint/config');
const expoConfig = require('eslint-config-expo/flat');

module.exports = defineConfig([
  expoConfig,
  {
    ignores: ['dist/*', '.expo/*', '.amplify/**', 'docs/**', '**/*.dc.html'],
  },
  {
    // `$amplify/env/<function>` modules are generated by Amplify when the backend is deployed.
    rules: {
      'import/no-unresolved': ['error', { ignore: ['^\\$amplify/'] }],
    },
  },
  {
    // Theme separation (Phase 1): colours come from src/theme through useTheme() or makeStyles.
    // Documented exception, outside the runtime theme because it is fixed at build time: app.json (adaptive
    // icon background, splash background and notification colour, #5A0020) and the native image assets
    // (app icons, splash wordmark, notification icon, favicon).
    ignores: ['src/theme/**'],
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector: 'Literal[value=/^#([0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/]',
          message: 'Hex colours belong in src/theme; read them with useTheme().',
        },
      ],
      'no-restricted-imports': [
        'error',
        {
          paths: [{ name: '@/theme', importNames: ['colors'], message: 'Deprecated: read colours with useTheme() (or makeStyles).' }],
        },
      ],
    },
  },
]);
