import {
  IBMPlexSansArabic_400Regular,
  IBMPlexSansArabic_500Medium,
  IBMPlexSansArabic_600SemiBold,
  IBMPlexSansArabic_700Bold,
} from '@expo-google-fonts/ibm-plex-sans-arabic';
import { Outfit_400Regular, Outfit_500Medium, Outfit_600SemiBold, Outfit_700Bold } from '@expo-google-fonts/outfit';
import { PlayfairDisplay_600SemiBold, PlayfairDisplay_700Bold } from '@expo-google-fonts/playfair-display';
import { QueryClientProvider } from '@tanstack/react-query';
import { Amplify } from 'aws-amplify';
import { useFonts } from 'expo-font';
import { Stack, usePathname, type ErrorBoundaryProps } from 'expo-router';
import * as SplashScreen from 'expo-splash-screen';
import { StatusBar } from 'expo-status-bar';
import { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import { Screen } from '@/components/Screen';
import { EmptyState } from '@/components/StateView';
import { ToastProvider, useToast } from '@/components/Toast';
import { WebFrame } from '@/components/WebFrame';
import { queryClient } from '@/data';
import { listenForSessionExpiry, restoreSession } from '@/features/auth/session';
import i18n, { currentLanguage, initI18n } from '@/i18n';
import { track } from '@/services/analytics';
import { installGlobalErrorHandler, reportError } from '@/services/monitoring';
import { useNotificationNavigation } from '@/services/notifications';
import { arabicFonts, colors, fonts } from '@/theme';
import { hideSplash } from '@/utils/splash';

import outputs from '../../amplify_outputs.json';

// The only Amplify.configure call: backend endpoints generated by `npx ampx sandbox` (ap-south-1).
Amplify.configure(outputs);

installGlobalErrorHandler();

SplashScreen.preventAutoHideAsync();

// Deep links (notifications, shared links) open on top of the tabs, so their back button returns to the app
// instead of leaving the user on a screen with no way back.
export const unstable_settings = { initialRouteName: '(tabs)' };

export default function RootLayout() {
  const [bootReady, setBootReady] = useState(false);
  const [fontsLoaded, fontError] = useFonts({
    PlayfairDisplay_600SemiBold,
    PlayfairDisplay_700Bold,
    Outfit_400Regular,
    Outfit_500Medium,
    Outfit_600SemiBold,
    Outfit_700Bold,
    IBMPlexSansArabic_400Regular,
    IBMPlexSansArabic_500Medium,
    IBMPlexSansArabic_600SemiBold,
    IBMPlexSansArabic_700Bold,
  });

  useEffect(() => {
    Promise.allSettled([initI18n(), restoreSession()]).finally(() => {
      setBootReady(true);
      track({ name: 'app_open' });
    });
  }, []);

  const ready = bootReady && (fontsLoaded || fontError !== null);
  const pathname = usePathname();

  // The launch route ("/") hides the native splash itself once its identical wordmark is on screen; any other
  // first route (deep link, notification) hides it as soon as the app is ready.
  useEffect(() => {
    if (ready && pathname !== '/') hideSplash();
  }, [ready, pathname]);

  if (!ready) return null;

  return (
    <QueryClientProvider client={queryClient}>
      <SafeAreaProvider>
        <WebFrame>
          <ToastProvider>
            <StatusBar style="dark" />
            <RootStack />
          </ToastProvider>
        </WebFrame>
      </SafeAreaProvider>
    </QueryClientProvider>
  );
}

function RootStack() {
  const { t } = useTranslation();
  const toast = useToast();

  useEffect(() => listenForSessionExpiry(() => toast(t('errors.SESSION_EXPIRED'))), [toast, t]);
  useNotificationNavigation();
  const titleFont = currentLanguage() === 'ar' ? arabicFonts.bodySemi : fonts.bodySemi;

  return (
    <Stack
      screenOptions={{
        headerShadowVisible: false,
        headerStyle: { backgroundColor: colors.background },
        headerTintColor: colors.textPrimary,
        headerTitleStyle: { fontFamily: titleFont, fontSize: 18 },
        headerBackButtonDisplayMode: 'minimal',
        headerBackTitle: t('common.back'),
        contentStyle: { backgroundColor: colors.background },
      }}
    >
      <Stack.Screen name="index" options={{ headerShown: false, animation: 'fade' }} />
      <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
      <Stack.Screen name="gym/[id]/index" options={{ headerShown: false }} />
      <Stack.Screen name="gym/[id]/plans" options={{ title: '' }} />
      <Stack.Screen name="gym/[id]/trainers" options={{ title: '' }} />
      <Stack.Screen name="trainer/[id]" options={{ title: '' }} />
      <Stack.Screen name="booking/index" options={{ title: '' }} />
      <Stack.Screen name="checkout/guest" options={{ title: '' }} />
      <Stack.Screen name="checkout/index" options={{ title: t('checkout.title') }} />
      <Stack.Screen name="checkout/success/[id]" options={{ headerShown: false, gestureEnabled: false }} />
      <Stack.Screen name="bookings/[id]" options={{ title: t('bookingDetails.title') }} />
      <Stack.Screen name="auth/sign-in" options={{ title: '' }} />
      <Stack.Screen name="auth/sign-up" options={{ title: '' }} />
      <Stack.Screen name="auth/forgot-password" options={{ title: '' }} />
      <Stack.Screen name="info/[slug]" options={{ title: '' }} />
      {/* Management and rating routes: default titles so a route name never shows (screens refine them). */}
      <Stack.Screen name="admin/index" options={{ title: t('admin.title') }} />
      <Stack.Screen name="admin/bookings" options={{ title: t('admin.bookings') }} />
      <Stack.Screen name="admin/reviews" options={{ title: t('admin.reviews') }} />
      <Stack.Screen name="admin/availability" options={{ title: t('admin.availability') }} />
      <Stack.Screen name="admin/gym/[id]" options={{ title: '' }} />
      <Stack.Screen name="admin/trainer/[id]" options={{ title: '' }} />
      <Stack.Screen name="review/[type]/[id]" options={{ title: '' }} />
      <Stack.Screen name="+not-found" options={{ headerShown: false }} />
    </Stack>
  );
}

// Last-resort crash screen (Expo Router error boundary): reported, then the shared empty/error state with Retry.
export function ErrorBoundary({ error, retry }: ErrorBoundaryProps) {
  useEffect(() => reportError(error, { area: 'render' }), [error]);
  return (
    <SafeAreaProvider>
      <Screen>
        <EmptyState icon="alert-circle-outline" title={i18n.t('errors.generic')} action={{ label: i18n.t('common.retry'), onPress: retry }} />
      </Screen>
    </SafeAreaProvider>
  );
}
